import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Disclaimer | MoneyTool",
  description:
    "Important disclaimer for MoneyTool's financial calculators. Read our terms, limitations, and liability disclaimers before using our tools.",
  alternates: {
    canonical: "https://www.moneytool.in/disclaimer",
  },
  openGraph: {
    title: "Disclaimer | MoneyTool",
    description: "MoneyTool financial tools disclaimer and limitations",
    type: "website",
    url: "https://www.moneytool.in/disclaimer",
  },
};

export default function Disclaimer() {
  return (
    <main
      style={{
        maxWidth: "900px",
        margin: "0 auto",
        padding: "60px 24px",
        color: "#f4f4f5",
        lineHeight: "1.7",
      }}
    >
      <h1
        style={{
          fontSize: "32px",
          fontWeight: "800",
          marginBottom: "24px",
          color: "#f4f4f5",
        }}
      >
        Disclaimer
      </h1>
      <p
        style={{
          color: "#a1a1aa",
          marginBottom: "32px",
          fontSize: "14px",
          background: "rgba(16,185,129,0.1)",
          border: "1px solid rgba(16,185,129,0.2)",
          padding: "16px",
          borderRadius: "8px",
        }}
      >
        ⚠️ Important: MoneyTool provides calculators for educational purposes only. The results are estimates based on the inputs you provide. Always verify calculations with official sources, banks, or financial professionals before making financial decisions.
      </p>

      <div style={{ display: "flex", flexDirection: "column", gap: "32px" }}>
        <section>
          <h2
            style={{
              fontSize: "20px",
              fontWeight: "700",
              marginBottom: "12px",
              color: "#10b981",
            }}
          >
            General Disclaimer
          </h2>
          <p style={{ color: "#a1a1aa", fontSize: "14px" }}>
            The information provided on MoneyTool, including all financial calculators, articles, and tools, is for educational purposes only. MoneyTool does not provide professional financial, investment, legal, or tax advice. The results generated by our calculators are estimates and should not be considered as exact figures.
          </p>
        </section>

        <section>
          <h2
            style={{
              fontSize: "20px",
              fontWeight: "700",
              marginBottom: "12px",
              color: "#10b981",
            }}
          >
            Accuracy & Completeness
          </h2>
          <p style={{ color: "#a1a1aa", fontSize: "14px" }}>
            While we strive to provide accurate information, MoneyTool:
            <ul style={{ marginTop: "12px", paddingLeft: "24px", color: "#a1a1aa" }}>
              <li>Does not guarantee the accuracy of calculations</li>
              <li>Is not responsible for outdated interest rates or tax information</li>
              <li>Cannot account for individual circumstances or edge cases</li>
              <li>Updates information periodically but not in real-time</li>
            </ul>
          </p>
        </section>

        <section>
          <h2
            style={{
              fontSize: "20px",
              fontWeight: "700",
              marginBottom: "12px",
              color: "#10b981",
            }}
          >
            EMI & Loan Calculators
          </h2>
          <p style={{ color: "#a1a1aa", fontSize: "14px" }}>
            EMI calculations are estimates based on standard formulas. Actual EMI may vary due to:
            <ul style={{ marginTop: "12px", paddingLeft: "24px", color: "#a1a1aa" }}>
              <li>Processing fees</li>
              <li>Insurance charges</li>
              <li>Bank-specific policies</li>
              <li>Floating vs. fixed interest rates</li>
              <li>Market fluctuations</li>
            </ul>
            Always confirm exact amounts with your bank or financial institution.
          </p>
        </section>

        <section>
          <h2
            style={{
              fontSize: "20px",
              fontWeight: "700",
              marginBottom: "12px",
              color: "#10b981",
            }}
          >
            Investment Calculators (SIP, PPF, FD, RD)
          </h2>
          <p style={{ color: "#a1a1aa", fontSize: "14px" }}>
            Investment returns shown by MoneyTool are based on:
            <ul style={{ marginTop: "12px", paddingLeft: "24px", color: "#a1a1aa" }}>
              <li>Assumed rates that may change</li>
              <li>Ideal scenarios without market volatility</li>
              <li>Standard formulas, not individual investment products</li>
            </ul>
            Actual returns depend on market conditions, individual products, and fund performance. Past performance does not guarantee future results.
          </p>
        </section>

        <section>
          <h2
            style={{
              fontSize: "20px",
              fontWeight: "700",
              marginBottom: "12px",
              color: "#10b981",
            }}
          >
            Tax Calculators
          </h2>
          <p style={{ color: "#a1a1aa", fontSize: "14px" }}>
            Tax calculations provided are estimates based on:
            <ul style={{ marginTop: "12px", paddingLeft: "24px", color: "#a1a1aa" }}>
              <li>Current financial year rules (FY 2025-26)</li>
              <li>Standard deductions and slabs</li>
              <li>Assumptions about your financial situation</li>
            </ul>
            Tax liability varies based on individual circumstances, deductions, investments, and amendments. Please consult a tax professional or CA for accurate tax planning.
          </p>
        </section>

        <section>
          <h2
            style={{
              fontSize: "20px",
              fontWeight: "700",
              marginBottom: "12px",
              color: "#10b981",
            }}
          >
            Limitation of Liability
          </h2>
          <p style={{ color: "#a1a1aa", fontSize: "14px" }}>
            MoneyTool, its creators, and contributors are not liable for:
            <ul style={{ marginTop: "12px", paddingLeft: "24px", color: "#a1a1aa" }}>
              <li>Financial losses or gains based on calculator results</li>
              <li>Incorrect decisions made using our tools</li>
              <li>Technical errors or inaccuracies in calculations</li>
              <li>Service interruptions or downtime</li>
              <li>Indirect or consequential damages</li>
            </ul>
          </p>
        </section>

        <section>
          <h2
            style={{
              fontSize: "20px",
              fontWeight: "700",
              marginBottom: "12px",
              color: "#10b981",
            }}
          >
            Third-Party References
          </h2>
          <p style={{ color: "#a1a1aa", fontSize: "14px" }}>
            MoneyTool is not responsible for the accuracy, completeness, or reliability of any third-party websites, resources, or information we may reference or link to.
          </p>
        </section>

        <section>
          <h2
            style={{
              fontSize: "20px",
              fontWeight: "700",
              marginBottom: "12px",
              color: "#10b981",
            }}
          >
            Your Responsibility
          </h2>
          <p style={{ color: "#a1a1aa", fontSize: "14px" }}>
            By using MoneyTool, you acknowledge that:
            <ul style={{ marginTop: "12px", paddingLeft: "24px", color: "#a1a1aa" }}>
              <li>You are using the tools at your own risk</li>
              <li>You will not rely solely on our calculators for financial decisions</li>
              <li>You will consult professionals for important financial matters</li>
              <li>You understand the limitations of online calculators</li>
            </ul>
          </p>
        </section>

        <section>
          <h2
            style={{
              fontSize: "20px",
              fontWeight: "700",
              marginBottom: "12px",
              color: "#10b981",
            }}
          >
            Professional Advice
          </h2>
          <p style={{ color: "#a1a1aa", fontSize: "14px" }}>
            For important financial decisions, always consult with:
            <ul style={{ marginTop: "12px", paddingLeft: "24px", color: "#a1a1aa" }}>
              <li>Certified Financial Advisors (CFP)</li>
              <li>Chartered Accountants (CA)</li>
              <li>Bank officials for loan-related queries</li>
              <li>Licensed investment professionals</li>
            </ul>
          </p>
        </section>

        <section>
          <h2
            style={{
              fontSize: "20px",
              fontWeight: "700",
              marginBottom: "12px",
              color: "#10b981",
            }}
          >
            Updates & Changes
          </h2>
          <p style={{ color: "#a1a1aa", fontSize: "14px" }}>
            MoneyTool updates information periodically, but tax rules, interest rates, and regulations may change. We are not liable for outdated information. It is your responsibility to verify current rates and rules.
          </p>
        </section>

        <section>
          <h2
            style={{
              fontSize: "20px",
              fontWeight: "700",
              marginBottom: "12px",
              color: "#10b981",
            }}
          >
            Contact & Support
          </h2>
          <p style={{ color: "#a1a1aa", fontSize: "14px" }}>
            For questions or concerns about this disclaimer, please contact us at contact@moneytool.in
          </p>
        </section>
      </div>
    </main>
  );
}
